### ISSUE TITLE
How to train this model?

### ISSUE THREAD

**Issue by jongeunpark** [adobe/trustmark#1]
I want to train this model.
I would greatly appreciate it if you could support the sources and scripts for training this model. :)

**Comment by jongeunpark** [comment]
I solved it

**Comment by xuanyuzhang21** [comment]
How to train this model? @jongeunpark

**Comment by Aliiiqbp** [comment]
I wanna train and test this model as well. Can you share your scripts and implementations to train/evaluate this model? Thanks.
@jongeunpark

**Comment by Maybeetw** [comment]
How to train this model? @jongeunpark
