### ISSUE TITLE
Error in README or missing folders

### ISSUE THREAD

**Issue by crandmck** [adobe/trustmark#3]
### Expected Behaviour

The README should be accurate.

### Actual Behaviour

The README contains this erroneous statement:

> This repo contains a [...] a browser deployable Javascript (js/) implementation of TrustMark for encoding, decoding and removing image watermarks. In addition, a C2PA (c2pa/) example is provided to demonstrate signing of a watermarked image using the CAI supplied python library for C2PA / Content Credentials.

There are neither `js` nor `c2pa` folders in this repo.

### How to fix

Either remove those phrases from the README, or (preferably) add the missing folders to the repo.

FYI @jcollomosse

**Comment by jcollomosse** [comment]
Thank you for the spot.
